### ISSUE TITLE
timerReactjs

### ISSUE THREAD

**Issue by Moyrasc** [andressoibelzon/timerReactjs#1]
Buen trabajo, Andrés

En esta parte : 
![image](https://user-images.githubusercontent.com/88618857/212467385-cecbc397-d0db-401c-8660-f7ae11867ca9.png)

También podrías haberlo hecho de la siguiente forma ---> 

![image](https://user-images.githubusercontent.com/88618857/212467572-fb26297b-672f-4d39-b63e-f060e983dfa0.png)

La forma en la que lo has hecho esta bien, simplemente te lo comento por si ves este código en otro lado :)

**Comment by andressoibelzon** [comment]
Noe, gracias por el comentario! Esta bueno esa forma, creo que es con el
destructuring, por ahi es mas simple de ver.

Saludos y que estes bien.
